version: "3"

services:
  nginx:
    image: nginx:1.16
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - custom-network
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    volumes:
      - ./code:/code
    networks:
      - custom-network
  mariadb:
    image: mariadb:10.4.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: mariadocker
    volumes:
      - ./mysql:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge
